### ISSUE TITLE
Where should the icon appear?

### ISSUE THREAD

**Issue by brylie** [hugoledoux/QGIS-getWKT#2]
I have installed the plugin, but do not see the icon. On what toolbar should it appear?

**Comment by hugoledoux** [comment]
in QGIS 2.14 I get it as ![follows](https://user-images.githubusercontent.com/1546518/33796953-16b4b2f8-dcff-11e7-9726-a6fc2492075e.png)

**Comment by brylie** [comment]
It might be helpful to mention that in the README. E.g. I was looking under the Plugins menu, and also had difficulty finding the toolbar icon hidden behind an ellipsis.

**Comment by hugoledoux** [comment]
good idea, done: 07799707b95039d8727f68a882931420a9f0a9c0
